### ISSUE TITLE
Add support for silent refresh

### ISSUE THREAD

**Issue by danieldobalian** [Azure-Samples/active-directory-javascript-graphapi-web-v2#1]
Hello.js supports silent refresh. Add integration to this sample to do silent refresh.

**Comment by danieldobalian** [comment]
hello.js had some problems doing silent refresh w/ AAD when prompt=none.  Couldn't find the cookie in browser.

**Comment by kaleemxii** [comment]
setting the **login_hint** = **preferred_username** claim value from the previous auth was able to refresh the token without the need of setting the prompt=none ..


Also to get the **preferred_username** have your scope set to '`profile user.read`' to work for both work and non work accounts

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
