### ISSUE TITLE
api() calls wont work

### ISSUE THREAD

**Issue by pwsimon** [Azure-Samples/active-directory-javascript-graphapi-web-v2#2]
1.) from my point of view the base url of Microsoft Graph-API is wrong.
it should be: 'https://graph.microsoft.com/v1.0/' isn't it.

2.) the access_token for api() calls added as query parameters instead of request header "Authorize Bearer".
How can i change this?

**Comment by jmprieur** [comment]
I don't know if this will help you, @pwsimon, but if you want to call the Microsoft Graph with a Microsoft School or Work account or with a Microsoft Personal account, you might want to checkout msal.js: https://github.com/AzureAD/microsoft-authentication-library-for-js. We release it in preview today. 
After you've read the [README.md](https://github.com/AzureAD/microsoft-authentication-library-for-js) for the library, you might want to check out this simple sample: (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginPopup.html), or this one: (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html). Both call the Microsoft Graph to send an email. For the fist one the experience is through a Popup, for the second one, though a redirect in the same browser page.

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
